CREATE TABLE IF NOT EXISTS ms_pickup_type (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pickup_type_name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO ms_pickup_type (pickup_type_name)
VALUES 
('One Time'),
('Weekly Scheduled');

CREATE TABLE IF NOT EXISTS ms_vehicle(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  vehicle_name VARCHAR(100) NOT NULL,
  max_weight INT UNSIGNED NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO ms_vehicle (vehicle_name, max_weight)
VALUES 
('Motor', 5),
('Mobil', 30);

CREATE TABLE IF NOT EXISTS tr_pickup_event (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  pickup_address TEXT NULL,
  pickup_weight DECIMAL(10,2) NOT NULL DEFAULT 0,
  pickup_type_id INT UNSIGNED NOT NULL,
  event_date DATE DEFAULT NULL,
  pickup_time TIME DEFAULT NULL,
  vehicle_id INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
