ALTER TABLE ms_users
ADD COLUMN village VARCHAR(255) AFTER subdistrict;

CREATE TABLE IF NOT EXISTS tr_payment_history (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  payment_type VARCHAR(50) DEFAULT 'SUBSCRIPTION',
  payment_method VARCHAR(50) NOT NULL,
  total_payment DECIMAL(15, 2) NOT NULL,
  transaction_status_id VARCHAR(50) NOT NULL,
  payment_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;