ALTER TABLE ms_vehicle
ADD COLUMN brand VARCHAR(100) NULL AFTER vehicle_name,
ADD COLUMN model VARCHAR(100) NULL AFTER brand,
ADD COLUMN license_plate VARCHAR(20) NULL UNIQUE AFTER model,
ADD COLUMN vin VARCHAR(17) NULL UNIQUE AFTER license_plate,
ADD COLUMN status ENUM('available', 'in_use', 'maintenance') DEFAULT 'available' AFTER max_weight,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE ms_driver
ADD COLUMN active_since TIMESTAMP NULL AFTER is_available;

ALTER TABLE ms_tier_list
ADD COLUMN target_weight DECIMAL(10, 2) NULL;